### ISSUE TITLE
Add Hall of fame on Donation Page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#11]
On the donation page, we would like to add a Hall Of Fame to highlight our donators.

![DONATION](https://user-images.githubusercontent.com/23256782/66324053-119bdd80-e925-11e9-9576-07202b5f4a3c.jpg)
(When you hover a color on the hall of fame, the text is changing). 

If you want to take this issue, just comment and I would give you the assets.

**Comment by Pavi114** [comment]
Can I work on this?

**Comment by Noelierx** [comment]
Sure thing! Here the link with the assets!
[https://www.dropbox.com/sh/m91flqqk02cr4ga/AABlDUIrR0l1nE8SrvmsoU50a?dl=0](https://www.dropbox.com/sh/m91flqqk02cr4ga/AABlDUIrR0l1nE8SrvmsoU50a?dl=0)

**Comment by Noelierx** [comment]
@Pavi114 how is that going for you?

**Comment by abbasCoder51** [comment]
@Noelierx Can I take this on please?

**Comment by Noelierx** [comment]
@abbasCoder51  yeah sure go ahead, the link with all the assets is right here : https://github.com/Noelierx/GameHer/issues/11#issuecomment-539164133

**Comment by abbasCoder51** [comment]
@Noelierx #52
