### ISSUE TITLE
Dropdown menu is not working on responsive

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#12]
On the mobile version, the dropdown menu "La Team" is not working. 
<img width="292" alt="Capture d’écran 2019-10-07 à 17 10 29" src="https://user-images.githubusercontent.com/23256782/66324289-70f9ed80-e925-11e9-8660-fe23273af717.png">

**Comment by MouadBH** [comment]
please assign me to it

**Comment by Noelierx** [comment]
Done :D Good luck to you!

**Comment by Noelierx** [comment]
@MouadBH how is that going for you?
