### ISSUE TITLE
Fix responsive on Esport page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#13]
When you are on esport page in responsive, we need to show only one player by line to avoid this kind of thing : 
![image0](https://user-images.githubusercontent.com/23256782/66324750-52482680-e926-11e9-8ff7-73bd9768cad8.png)

**Comment by reliq** [comment]
I could tackle this one.

**Comment by Noelierx** [comment]
Sure thing! Go ahead
