### ISSUE TITLE
Add Biography for redactor on article pages

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#14]
On the article page (blog), we would like to add a biography for our writers that they can edit in their profile. 
![STUCTUREARTICLE](https://user-images.githubusercontent.com/23256782/66325478-9be54100-e927-11e9-8fb4-00c67331fba4.jpg)
(Requires adding a field to the database and touching the Profile and _author Twig files)

**Comment by ffeliks** [comment]
Hi! I'd like to work on this issue
