### ISSUE TITLE
Redesign section 2 on Recruitment page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#17]
Expected: As a user when I hover the icons on the recruitment page I would like to see the description of the icon. 
![RECRUTEMENT (1)](https://user-images.githubusercontent.com/23256782/66410822-0d3df600-e9f3-11e9-8503-137ca9245a79.jpg)

Actual: We have the descriptions in hard copy and there is no hover effect.

**Comment by m1ga** [comment]
With some comments in the PR https://github.com/Noelierx/GameHer/pull/20
