### ISSUE TITLE
Fix mobile navigation

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#18]
On mobile navigation, we have a small space between the navigation and the header with the logo.
<img width="420" alt="Capture d’écran 2019-10-08 à 17 44 40" src="https://user-images.githubusercontent.com/23256782/66411045-6443cb00-e9f3-11e9-95d2-68314e27a775.png">

**Comment by neilong31** [comment]
Hello! I'd love to try and tackle this issue.

**Comment by Noelierx** [comment]
Sure go ahead!
