### ISSUE TITLE
Add new plugin for CKEditor

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#24]
We are using CKEditor to write our articles. We need to add new plugins to make life easier for our editors. 

Here's the list of the plugins we would like to add: 
- [https://ckeditor.com/cke4/addon/pastefromgdocs](https://ckeditor.com/cke4/addon/pastefromgdocs)
- [https://ckeditor.com/cke4/addon/justify](https://ckeditor.com/cke4/addon/justify)
- [https://ckeditor.com/cke4/addon/preview](https://ckeditor.com/cke4/addon/preview)

If you find any other plugins that might be interesting, don't hesitate!

[https://symfony.com/doc/current/bundles/FOSCKEditorBundle/usage/plugin.html](https://symfony.com/doc/current/bundles/FOSCKEditorBundle/usage/plugin.html)

**Comment by amstr4d** [comment]
I'm working on it ! Those plugins need to be in all CKeditor instances ?

**Comment by Noelierx** [comment]
They needs to be in all CKeditor instances if it's possible :D
