### ISSUE TITLE
Revamp profile page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#25]
<img width="1672" alt="Capture d’écran 2019-10-09 à 16 44 31" src="https://user-images.githubusercontent.com/23256782/66492095-222e8e00-eab4-11e9-8d41-07a06747449f.png">
Our actual profile page is quite ugly. 
We would love to have a nice profile page, easy to edit. 
We are using Materializecss, so you just have to follow their guidelines about forms. 

There is no design, wee just want a nice **responsive** profile page, with the fields already here.

**Comment by flavianunes** [comment]
Can I work on it? :dancer:

**Comment by Phobi-Wan-Kenobi** [comment]
I would like to give this a go :)

**Comment by lauramurinova** [comment]
may I work on this?

**Comment by Noelierx** [comment]
Yeah sure

**Comment by lauramurinova** [comment]
Sorry eventually I cant, is it free for anyone else. I apologize.

**Comment by Noelierx** [comment]
No problem

> Sorry eventually I cant, is it free for anyone else. I apologize.

No problem :)

**Comment by codeasashu** [comment]
Can I start on this?

**Comment by Noelierx** [comment]
> Can I start on this?

Yeah sure go ahead! :D

**Comment by Noelierx** [comment]
@codeasashu how is that going for you?

**Comment by codeasashu** [comment]
@Noelierx Let me know your thoughts
