### ISSUE TITLE
Remove duplicate member on About us page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#27]
When a member is part of 2 or more esport team, he appears twice on the about page. 
Find a way to remove the duplicate member. 

On the examples below, the member "Jonas Milan" appears on "Equipe principale" and on "Equipe Académique". So by default he appears twice on /about :
<img width="1178" alt="Capture d’écran 2019-10-16 à 15 31 57" src="https://user-images.githubusercontent.com/23256782/66924077-447f5900-f02a-11e9-809b-dcdbb81e9bec.png">
<img width="1138" alt="Capture d’écran 2019-10-16 à 15 32 06" src="https://user-images.githubusercontent.com/23256782/66924078-4517ef80-f02a-11e9-81de-66073615f3fe.png">
<img width="555" alt="Capture d’écran 2019-10-16 à 15 32 21" src="https://user-images.githubusercontent.com/23256782/66924079-4517ef80-f02a-11e9-99f8-9307b6a3b09f.png">

**Comment by elstamey** [comment]
I would like to complete this one

**Comment by abbasCoder51** [comment]
Hi, finally managed to setup this project on my local machine. If possible, I would like to work on this?

**Comment by elstamey** [comment]
I've been working on it, @abbasCoder51 It was definitely difficult to set up the project.

**Comment by chypriote** [comment]
Best way to do this would be creating a new Team entity with a ManyToMany relation with EsportMembers. However I think this not worth the effort for such a small edge case.

Either use the fix from #28 every time we display esport members, or do not create the same person twice
