### ISSUE TITLE
As an admin, I want to add / edit / delete manually a user

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#32]
**Expected:** As I'm an admin, I want to be able to add / delete / edit a user on the admin panel instead of do it on phpmyadmin.

**Actual**: As an admin, when I want to add / edit / delete a new user I have a page with no options to do it.

**Comment by chypriote** [comment]
More details:
Add views in `templates/admin` to display the `User` entities in base.
A simple table similar to the ones for members is more than enough. The only required display is `displayName` and `role`.
Add a third column with rounded buttons (similar to [posts](https://github.com/Noelierx/GameHer/blob/master/templates/admin/posts/index.html.twig#L47)) to update the User's roles and set it to either `ROLE_USER`, `ROLE_REDACTEUR` or `ROLE_ADMIN`

Note that only the users with `ROLE_ADMIN` permission should be allowed to access this route and update another user's roles, and that only ``ROLE_SUPER_ADMIN` should be allowed to edit the role from `ROLE_ADMIN`

**Comment by liloo2040** [comment]
Hello! May I work on this one ?

**Comment by liloo2040** [comment]
Thank you @Noelierx ! I've started working on it! Do you know if there is another way to connect to the admin part without having a discord json data displaying ? Thank you in advance for your reply!

**Comment by Noelierx** [comment]
@chypriote 🔼
