### ISSUE TITLE
Add the possibility to choose a time to schedule article

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#35]
As an editor on the website, I want to be able to select a time in addition to a date.
We want to use the time picker from materializecss : https://materializecss.com/pickers.html 

<img width="1652" alt="Capture d’écran 2019-10-17 à 10 22 38" src="https://user-images.githubusercontent.com/23256782/66991355-3122cb00-f0c8-11e9-923c-59f52465098e.png">
<img width="655" alt="Capture d’écran 2019-10-17 à 10 23 09" src="https://user-images.githubusercontent.com/23256782/66991356-3122cb00-f0c8-11e9-9ec1-1cd2090aac49.png">

**Comment by abbasCoder51** [comment]
@Noelierx want to have an attempt at this.

**Comment by Noelierx** [comment]
Yeah sure go ahead!

**Comment by abbasCoder51** [comment]
@Noelierx is there a seeder file? my database is empty and I am not able to access admin (access denied) without removing IsGranted()

**Comment by Noelierx** [comment]
@chypriote ⬆️

**Comment by chypriote** [comment]
Hello, no there is no seed file. You will have to manually edit the user in the DB to set his role to `ROLE_ADMIN` or `ROLE_SUPER_ADMIN`. That's not optimal but probably the quickest way to do it.
 
Long term solution could be to make it so the first user to login is automatically granted ROLE_SUPER_ADMIN

**Comment by Noelierx** [comment]
@abbasCoder51 did you have time to check @chypriote 's answer?
