### ISSUE TITLE
Display last articles on the homepage

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#36]
As a user, I want to be able to see the last published articles (and not shedule ones) on the homepage of the website.
<img width="1661" alt="Capture d’écran 2019-10-17 à 10 30 52" src="https://user-images.githubusercontent.com/23256782/66991974-519f5500-f0c9-11e9-87c8-537452bee8b9.png">

font-size of title should be 50px.

**Comment by liloo2040** [comment]
Hello! May I work on this one too ?

**Comment by Noelierx** [comment]
Of course :D

**Comment by liloo2040** [comment]
Hello! I'm almost done with this part, just some fixes to do with images displaying when some articles are displayed.
