### ISSUE TITLE
Center image and social media

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#38]
On the page "About us" : 
- On the desktop version I want to align (and center) the social medias icon with the image.
<img width="1076" alt="Capture d’écran 2019-10-17 à 11 12 03" src="https://user-images.githubusercontent.com/23256782/66995339-215ab500-f0cf-11e9-8a2b-85ef617afdd5.png">

- On the mobile version I want to align (and center) the member image with the social medias icons
<img width="419" alt="Capture d’écran 2019-10-17 à 11 11 54" src="https://user-images.githubusercontent.com/23256782/66995358-291a5980-f0cf-11e9-8590-f2f6e013d33c.png">

We can have up to 5 different social media

**Comment by aman-thakur123** [comment]
I would like to work on this.

**Comment by liloo2040** [comment]
Hello! May I work on this issue ?

**Comment by Noelierx** [comment]
@liloo2040 Yeah sure go ahead! :D

**Comment by liloo2040** [comment]
Thank you! I've just forked your repo, but I have some install issues.

**Comment by Noelierx** [comment]
> Thank you! I've just forked your repo, but I have some install issues.
> 
> EDIT : Install issues fixed. About Discord, is it necessary that I register to work on the project ? Thank you for your reply!

No it's not necessary for this page :D you just have to add a bunch of users in the database by yourself with social media

**Comment by liloo2040** [comment]
Thank you for your reply!

**Comment by liloo2040** [comment]
I'm trying adding users and the 'uuid' field is causing me issues (#1364 - Field 'uuid' doesn't have a default value  - after trying to change field and adding values). How can I solve this ? Thank you in advance!

**Comment by Noelierx** [comment]
> I'm trying adding users and the 'uuid' field is causing me issues (#1364 - Field 'uuid' doesn't have a default value - after trying to change field and adding values). How can I solve this ? Thank you in advance!
> 
> EDIT: I think I'll use fixtures to add some data. It will be easier for me. I'll keep you updated.

Hi! So sorry about that. It's the Universal Unique Identifier to generate fake ones you can use this tool : https://www.uuidgenerator.net/
