### ISSUE TITLE
Fix error when I send an email

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#47]
Due to #34 when I want to send an email from the contact form on the contact and on the recruitment pages I always have the error flashbar saying "Un problème est survenu" (An error occurred, in english).  

I want the email to be sent directly to contact@gameher.fr or recrutement@gameher.fr

**Comment by adriaanvermeire** [comment]
Can I work on this?

**Comment by Noelierx** [comment]
Yeah sure go ahead!

**Comment by adriaanvermeire** [comment]
Didn't notice this was PHP project! Won't be able to work on this right now, sorry!

**Comment by akshayachar2011** [comment]
@Noelierx Would like work this now. Can you assign to me. 
Thanks.

**Comment by akshayachar2011** [comment]
@Noelierx When i checked this issue on my local. It was working fine . Email was getting tricked. Can you check if the value in the MAILER_URL is added correctly. Might be SMTP might not be configured correctly. 

For reference: https://blog.mailtrap.io/send-emails-in-symfony/
