### ISSUE TITLE
Fix pagination when I'm on an author page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#49]
### Expected Behavior
When I'm in the author page (https://gameher.fr/blog?author=AUTHORNAME) and when I click on the second page, I want to see all the articles written by THIS unique author.
### Actual
When I'm in the author page and when I click on the second page (in the pagination), I can see all the articles written by all authors and not the selected one.
### Steps to reproduce
1. Go to https://gameher.fr/blog
2. Select an article and click on the link of the author in the title
3. At the bottom, click on the "2" or "3" from the pagination
4. Boum, you have all the articles from the page /blog and they have nothing to do on the /blog?author=AUTHORNAME page.

**Comment by L3RAZ** [comment]
#51 Hello, I made a pull request for this issue.
