### ISSUE TITLE
Revamp design of Homepage

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#54]
We actually want to revamp the design of our homepage. 

**Actual:** 
![screencapture-gameher-fr-2020-01-17-09_59_23](https://user-images.githubusercontent.com/23256782/72598431-17379500-3910-11ea-90b7-f782abd3a7d4.png)

**Expected:**
![DESKOP_HOMEPAGE](https://user-images.githubusercontent.com/23256782/72598627-6f6e9700-3910-11ea-9a59-46d572c89374.png)
And for the mobile version
![MOBILE_HOMEPAGE_PROPOSITION](https://user-images.githubusercontent.com/23256782/72598700-99c05480-3910-11ea-9e1c-0b68c44bc8e1.png)

**Comment by liloo2040** [comment]
Hello! I would like to help you on this task!

**Comment by Noelierx** [comment]
@liloo2040 hi! For sure, I'm almost done for the desktop version, but my mobile version isn't looking like the second screen capture, if you want to help on it feel free

**Comment by Noelierx** [comment]
@liloo2040 But if it can help you, feel free to redo also the desktop version, mine is not exactly pixel perfect than the screenshot

**Comment by liloo2040** [comment]
Thank you! I will do it as soon as possible!
