### ISSUE TITLE
Make search bar usable 

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#63]
Today we have a search bar on our blog, but it's not usable. 

![image](https://user-images.githubusercontent.com/23256782/75821763-19aa5d00-5d9f-11ea-96f5-9a4231d9ba4a.png)

**Comment by thePlebDev** [comment]
if this is still open can I work on it ?

**Comment by ShaneCreedon** [comment]
@Noelierx I'll fix this, please assign to me!

**Comment by Noelierx** [comment]
Yes go ahead! 
Good luck!

**Comment by me-v-en** [comment]
Can I take a look at this ?

**Comment by Noelierx** [comment]
Of course you can @me-v-en !
Good luck!

**Comment by chandresh1339** [comment]
Can I also work on other feature if you want me?

**Comment by Noelierx** [comment]
@chandresh1339 you can take a look to our [issues](https://github.com/Noelierx/GameHer/issues) to see all our features. 
If you want to propose some, feel free to open a new issue.

**Comment by Noelierx** [comment]
Fix in #130
