### ISSUE TITLE
[Feature] Create a slider to display partners on footer

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#65]
---
name: Feature request
about: Suggest an idea for this project
title: Create a slider to display partners on footer
labels: enhancement, good first issue, Hacktoberfest
assignees: 

---

**Is your feature request related to a problem? Please describe.**
When we have more than 4 partners, we display the first four on top and the others at the bottom. It's not really aesthetic as you can see on the screenshot below. 
![image](https://user-images.githubusercontent.com/23256782/76312125-a474e580-62d2-11ea-8d4b-9e8674166a15.png)

**Describe the solution you'd like**
We would like to have a slider to display all the logos on the same line. By modifying the actual footer.

**Comment by pallavithakare28** [comment]
Hey @Noelierx As I am beginner to open source but want to try for this issue. Can you please assign it to me?

**Comment by Noelierx** [comment]
@pallavithakare28 Of course I can, you can wait October first to start if you want your Pull Request counted in the Hacktoberfest

**Comment by pallavithakare28** [comment]
Thank you @Noelierx Yes sure I'll wait
