### ISSUE TITLE
Fix spacing between elements in footer

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#7]
Visual improvement of the footer, more spacing between the elements

Right now the footer is like this : 
![image](https://user-images.githubusercontent.com/23256782/62877832-29d9ec80-bd28-11e9-8e75-ec144b2ff1f3.png)

And it's supposed to be like this : 
![image](https://user-images.githubusercontent.com/23256782/62877846-33635480-bd28-11e9-8a7b-e2e46ba69c94.png)

**Comment by cryolis** [comment]
Hi, can I puck up this issue?

**Comment by Noelierx** [comment]
Sure thing! I assign this one to you :D

**Comment by Noelierx** [comment]
@cryolis how is that going for you?

**Comment by cryolis** [comment]
I think im almost done, the only thing is partner images are not showing up in my local environment, so I cant really see the spacing between them.

**Comment by cryolis** [comment]
![Capture](https://user-images.githubusercontent.com/10778116/66964422-9503b000-f044-11e9-9ba3-911754ae25f2.JPG)

This is the way I have it at the moment. Is it ok or you did you want anything else?

**Comment by Noelierx** [comment]
> ![Capture](https://user-images.githubusercontent.com/10778116/66964422-9503b000-f044-11e9-9ba3-911754ae25f2.JPG)
> 
> This is the way I have it at the moment. Is it ok or you did you want anything else?

Sounds great for me 👍 Don't hesitate to make the PR :D

**Comment by cryolis** [comment]
#40
