### ISSUE TITLE
As an Editor, I want to schedule article with a time picker.

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#74]
### As an Editor, I want to be able to schedule an article with a time picker in addition to the date picker.

The UI doesn't need to be perfect because it's in admin side. In fact, you can use the Time Picker from [ Materializecss](https://materializecss.com/pickers.html) as we already use the Date Picker from the same framework. 

It will require some back-end work. Unfortunately we don't have a seed file and you will have to manually edit the user in the database to set his role to ROLE_ADMIN or ROLE_SUPER_ADMIN. That's not optimal but probably the quickest way to do it.

**Comment by Sonny812** [comment]
Hello, @Noelierx!
I would like to work on this issue. Can you assign it to me?

**Comment by Noelierx** [comment]
Yeah sure @Sonny812 Go ahead! 
good luck
