### ISSUE TITLE
As a User, I want to see a custom 404 page when I'm lost.

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#75]
### As a user, I want to see a custom 404 page when I'm lost on the website. 

- It will require a lot of front-end work. You can reuse some template in twig already existing to do this. 
- It will require some back-end work to enable the fact that we can use a custom 404 page. 

Here's the design for the 404 page: 
![73266562-64045100-41d7-11ea-9317-20bf3810485c](https://user-images.githubusercontent.com/23256782/85272364-5ef0b880-b47c-11ea-983e-4ebe627cc3b7.png)

**Comment by me-v-en** [comment]
Hi, can I work on this ? 🙂

**Comment by Noelierx** [comment]
Hi @me-v-en of course you can :D 

Here's the link for the illustration: [https://www.dropbox.com/s/vq0ob7yfd9d7vtr/STYX.svg](https://www.dropbox.com/s/vq0ob7yfd9d7vtr/STYX.svg?dl=0)

Feel free to wait october 1rst to start working on it ;)

**Comment by Lilykhan786** [comment]
Hey, can I help with the front-end?

**Comment by Noelierx** [comment]
@Lilykhan786 Fell free to reach out to @me-v-en to see his needs!
For my part I don't see any problem for you to work on it together ;)

**Comment by me-v-en** [comment]
I'm sorry @Lilykhan786, I've finished the front end, I'm just waiting for October to make the PR 😕

**Comment by Lilykhan786** [comment]
It's ok I have found few more repos to work on :P
