### ISSUE TITLE
Pagination isn't working on the blog with the search

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#77]
### Expected Behavior
When I'm in the search page ((https://gameher.fr/blog?query=test) and when I click on the second page, I want to see all the articles visible with THIS unique search and not others.

### Actual
When I'm in the search page and when I click on the second page (in the pagination), I can see all the articles of the website and not only my search

### Steps to reproduce
Go to https://gameher.fr/blog
Type a search
At the bottom, click on the "2" or "3" from the pagination
Boom, you have all the articles from the page /blog, and they have nothing to do on the /blog?query=test page.

### This bug is related to this issue : https://github.com/Noelierx/GameHer/issues/49

**Comment by Krsnananda** [comment]
Hi, can I work on this issue? :)
