### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by Kocal** [Noelierx/GameHer#79]
**Is your feature request related to a problem? Please describe.**
I am bit suprised I don't see any Continuous Integration (CI) on a matured-project like this.

By using CI, we could automatically:
- lint yaml files, with `bin/console lint:yaml config`  
- lint Twig files, with `bin/console lint:twig templates`
- lint Symfony container, with `bin/console lint:container`
- run a static analysis tools for PHP, like [PHPStan](https://phpstan.org/) or [Psalm](https://psalm.dev/)
- run tests for PHP, like [PHPUnit](https://phpunit.de/), [phpspec](http://www.phpspec.net/en/stable/), or [Behat](https://docs.behat.org/en/latest/)...
- lint the JS files, with [ESLint](https://eslint.org/)
- lint the CSS files with [Stylelint](https://stylelint.io/)
- run tests for JS, with [Jest](https://jestjs.io/) or another tool
- run [Webpack Encore](https://github.com/symfony/webpack-encore) to see if the JS/CSS assets are _buildable_

If we run the CI for each pull request, we can prevent any regression to be shipped in production.

**Describe the solution you'd like**
Use [GitHub Actions](https://github.com/features/actions). I've used for many months and I'm really happy about it.

**Describe alternatives you've considered**
Use [Travis](https://travis-ci.org/) but it's slow, or [CircleCI](https://circleci.com/) but it's not free.

**Additional context**
Nope.

**Comment by Noelierx** [comment]
Hey sorry for the late reply. 
We can get in touch to talk about this if you'd like too work on it, I have some plans for CircleCi and Travis.
I never had a chance to take some time and see what we can do with that, but I would be happy to.
