### ISSUE TITLE
Add a streaming planning

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#84]
# Add a streaming planning

## Problems to solve

The Streamers of Game'Her want to be able to add schedule their streams into a planning without having to use something like google agenda, or twitch schedule, or some other website. They want to be able to add their streaming slots into the website Game'Her on the same base that our writers are doing.  

### Admin Side
- [ ] Create the streaming / planning page on the admin dashboard (this page is available only for ROLE_STREAMER_USER and ROLE_SUPER_ADMIN_USER). Be careful, a user can have multiple roles and can be Streamer and Rédacteurs (so he will need to have access to this page).
- [ ] Create ROLE_STREAMER_USER
- [ ] Create a form to add the streaming slot (information needed below) on the page you previously created
  - Stream Name
  - Game or Activity Name
  - Date and hours
  - Optional : a slot for image background

### Website side? 
- [ ] Display a weekly streaming planning on [https://gameher.fr/webtv](https://gameher.fr/webtv) or create a new dedicated page according to the difficulty
- [ ] Only display the planning of the current week, hide others weeks by default. But we need an option to display the upcoming or previous weeks (slider, arrow, your choice be free).
- Warning : we don't have UI for the planning keep in mind we are using [materializecss](https://materializecss.com/) so be consistent with their guidelines.  A calendar form would be ideal, but if you have other propositions I'm open to it. 

## Want to contribute on this task? 

If this task it to enormous we can explode it into several tasks but some depends on others.

**Comment by Artelisan** [comment]
Hello,
can i try to do this issue? Can u assign it to me please?

**Comment by Noelierx** [comment]
Hello @Artelisan yeah of course! 
Feel free to tell me if the issue is too enormous for only one people.

**Comment by Artelisan** [comment]
Has anyone had a similar problem? I can't move.

![Snímka01](https://user-images.githubusercontent.com/65886735/97147904-8cbb7600-176a-11eb-8788-63d3a0acc6b1.PNG)
![Snímka](https://user-images.githubusercontent.com/65886735/97147908-8d540c80-176a-11eb-83f0-4ad8c4b4f581.PNG)

**Comment by Noelierx** [comment]
Hello @Artelisan in order to be able to help you best, I need to know which OS you are using, same if you're using Wamp, Xampp or something else and your PHP version!

**Comment by Artelisan** [comment]
My OS is Windows 10 Pro, i tried wampp and xampp and my PHP version 7.4.9. This error occurs when I go through discord authentication. 
![Snímka03](https://user-images.githubusercontent.com/65886735/97154936-de68fe00-1774-11eb-843f-ef885277052d.PNG)

**Comment by Noelierx** [comment]
Have yout tried this: https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate ?

**Comment by Artelisan** [comment]
Yes, he tried, but I've already solved it. The problem was in the slashes. Thanks for you help.
