### ISSUE TITLE
Add multiple author to an article

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#85]
# Add multiple author to an article

## Problems to solve

The authors at Game'Her are writing some articles with other people. They want to be able to add other authors on the same article. 

### Admin Side
- [ ] Modify the database in accordance
- [ ] Add a new field to offer them the possibility to add new authors. As we don't have a design for that you can be free to choose the best option between:
 - a dropdown menu showing every people with the role "ROLE_REDACTEUR"
 - a list with checkbox showing every people with the role "ROLE_REDACTEUR"
 - a search field with autocompletion accepting only users with the role "ROLE_REDACTEUR"

### Website side? 
- [ ] Display multiple authors if an article have some. But you should only show the bio of the first one. 

## Want to contribute on this task? 

If this task it to enormous we can explode it into several tasks but some depends on others.

**Comment by brano1403** [comment]
can u assign me to this issue ?

**Comment by Noelierx** [comment]
Hello @brano1403 ! 
Of course I can, good luck :D

**Comment by brano1403** [comment]
@Noelierx  thanks :)
