### ISSUE TITLE
As an admin I want to be able to see / delete / edit a user on the admin panel

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#86]
As I'm an admin, I want to be able to see / delete / edit a user on the admin panel instead of do it on phpmyadmin.

Note that only the users with `ROLE_ADMIN` permission should be allowed to access this route and update another user's roles, and that only `ROLE_SUPER_ADMIN` should be allowed to edit the role from `ROLE_ADMIN`

Unfortunately we don't have a seed file and you will have to manually edit the user in the database to set his role to ROLE_ADMIN or ROLE_SUPER_ADMIN. That's not optimal but probably the quickest way to do it.

**Comment by Zuruckt** [comment]
Hey can i work on this? Got the project setup done and started to take a look into it.

I've noticed that there is already view half-way complete that I suppose is the one wanted?
![image](https://user-images.githubusercontent.com/11967494/94316429-b3fc0900-ff5a-11ea-8aa2-96c09c52488c.png)

Also, does this application use any css framework such as Bootstrap or is everything custom?

**Comment by SPie** [comment]
I would like to work on this issue if you are OK with it.
I saw, there is already a list view for admin users, but the action buttons don't work. Should this be the view for the admin users and I would have to just add the functionality of the actions?

**Comment by Noelierx** [comment]
Hello @SPie ! 
Thanks a lot for your interest in Game'Her project!

You're totally right, there is already a list view for admin users and it's this one we need to modify to make the buttons work !
