### ISSUE TITLE
Create Media Page

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/GameHer#89]
We want to create a new page located in the footer called "Media Kit". The objective of this page is to allow people to download our logos and colors easily. We keep the footer as it is right now, we just add the link redirecting to the new page. 

For the colors, you can add the hexadecimal color and allow the user to add them into their clipboard when clicking on the color.

If you want to work on this, I will provide you the Figma link and the assets.

- [ ] Create a view and a controller for this page
- [ ] Add logo assets so people can download them (I can provide a Dropbox link with everything on it).
- [ ] Add the text in the translation file

<img width="1920" alt="MEDIA_KIT" src="https://user-images.githubusercontent.com/23256782/93988175-b444aa80-fd88-11ea-9162-60a8c4dc7323.png">

**Comment by miquelp** [comment]
Hi! 

I've just discovered this project and it's such an amazing initiative, I'd really like to contribute!

I've been a PHP Developer for like 3 years nowad so I believe I can help with some of the issues. Could i get this particular one assigned?

Just in case you are cool with me going ahead with this issue, I'd be awesome if you could provide me that Figma link and the assets that need to be download in the page, so I can start working on it as soon as possible.

Thanks!

**Comment by Noelierx** [comment]
Hi @miquelp !
Of course, you can work on it! Thank you a lot for your support!

Here's the dropbox link with the logos: [Dropbox](https://www.dropbox.com/sh/t5a78o5347iyc16/AABmy-rpZBAYWBHzotwluglIa?dl=0)
Here's the Figma link: [Figma](https://www.figma.com/file/LVn5WDkftTYl3Db2CCvWsa/WebSite_GameHer?node-id=0%3A1)

Thank you and good luck!

**Comment by miquelp** [comment]
Hi! Been working on this lately but some doubts arised. 

Is there any preference for the download when user clicks on "Télécharger" button? Maybe a zip/rar with all the logos? Or all logos should be downloaded as separate files?

Also, original issue says:

_The objective of this page is to allow people to download our logos **and colors** easily_

Unless I'm missing something, what does "download colors" really mean in this context? Isn'it it enough that users see hex code on the media page?

Thanks!
