### ISSUE TITLE
Sticky Navbar ?

### ISSUE THREAD

**Issue by ShubhamPalriwala** [Noelierx/GameHer#90]
Users often tend to get lost in the website if they don't find a navigation bar just to make things easier for them

A Sticky Navbar which stays always on top of the screen makes the website more accessible.

So, if it helps our end users, I'd like to work on modifying the navbar !

**Comment by Noelierx** [comment]
Hi @ShubhamPalriwala !
It's something we didn't think about, you can work on it if you'd like 😄
Just beware of the dropdown we have on the navigation it can be tricky with the sticky navbar.

**Comment by testerslol123** [comment]
@Noelierx Hi Noe, I would like to take this challenges to sticky navbar? It has been 17 days.

**Comment by ShubhamPalriwala** [comment]
@testerslol123 , lets both of us do it and whosoever gets it done first is the winner?
If @Noelierx is okay with it?

**Comment by Noelierx** [comment]
Hi! 
I actually prefer that you try to work together on this if possible. 
Then why not add a little competition but I don't want either of you to feel discouraged about it.

**Comment by ShubhamPalriwala** [comment]
No No, I won't feel discouraged lol !
@testerslol123 depends on you

**Comment by karlyn33** [comment]
Hi @Noelierx  . i helped you last year during Hacktoberfest.
I don't know if they still work on this... Here is my solution.
